# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20151209_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('backsquat', models.IntegerField(default=0)),
                ('deadlift', models.IntegerField(default=0)),
            ],
        ),
    ]
