# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_athleteprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='backsquat',
            new_name='backsquat1rm',
        ),
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='deadlift',
            new_name='deadlift1rm',
        ),
    ]
