# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20151222_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='backsquat1rm',
            new_name='backsquat_1rm',
        ),
        migrations.RenameField(
            model_name='athleteprofile',
            old_name='deadlift1rm',
            new_name='deadlift_1rm',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='angie',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='annie',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='backsquat_3rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='backsquat_5rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='badger',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='barbara',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='bulger',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='chelsea',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='cindy',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='clean_and_jerk_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='daniel',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='danny',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='deadlift_3rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='deadlift_5rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='diane',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='dt',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='elizabeth',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='eva',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='fight_gone_bad',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='filthy50',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='fran',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='front_squat_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='front_squat_3rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='front_squat_5rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='grace',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='hang_clean_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='hang_snatch_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='helen',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='isabel',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='jack',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='jackie',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='josh',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='jt',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='karen',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='kelly',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='lumberjack20',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='mary',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='mcghee',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='michael',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='mr_joshua',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='murph',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='nancy',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='nate',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='nicole',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='power_clean_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='power_snatch_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='push_jerk_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='push_press_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='randy',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='ryan',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='shoulder_press_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='snatch_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='split_jerk_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='squat_clean_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='squat_snatch_1rm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='the_seven',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='tommy_v',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
